[features]
seeds = false
[programs.devnet]
solana_raffles = "ARH14sTAAUggnzTa7FCqsT5zkXhyZQE7pxXj8u31GLCy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/zaryab/Desktop/SolanaWallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
